export const LOG_IN = "LOG_IN";
export const EXCHANGE = "EXCHANGE";
export const SEND_ADDRESS = "SEND_ADDRESS";
export const UPDATE_USER = "UPDATE_USER";
export const LOGGED_IN = "LOGGED_IN";
export const RESET = "RESET";
export const CANCEL_EXCHANGE = "CANCEL_EXCHANGE";
export const CANCEL_SEND_ADDRESS = "CANCEL_SEND_ADDRESS";
// export const GET_DATA_POST = "GET_DATA_POST";
